package com.ust.pms.Model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;



import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Entity
@Getter
@Setter
@NoArgsConstructor
@ToString
@RequiredArgsConstructor
public class Numbers {

	@Id
	@GeneratedValue
	private int aautoGeneratedID;
	private @NonNull int firstnumber;
	private @NonNull int secondNumber;
	private @NonNull int thirdNumber;
	private @NonNull int fourthNumber;
	private @NonNull int fifthNumber;
	
	private @NonNull int result;
	
}
