/*
 * Product App Info
 * CRUD operations on product
 *
 * OpenAPI spec version: 1.0
 * Contact: tufailahmedkhan@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.swagger.client.codegen.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * product model in appp
 */
@ApiModel(description = "product model in appp")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-21T09:58:50.480+05:30")
public class Product {
  @JsonProperty("price")
  private Integer price = null;

  @JsonProperty("productId")
  private Integer productId = null;

  @JsonProperty("productName")
  private String productName = null;

  @JsonProperty("quantityOnHand")
  private Integer quantityOnHand = null;

  public Product price(Integer price) {
    this.price = price;
    return this;
  }

   /**
   * price of product
   * @return price
  **/
  @ApiModelProperty(required = true, value = "price of product")
  public Integer getPrice() {
    return price;
  }

  public void setPrice(Integer price) {
    this.price = price;
  }

  public Product productId(Integer productId) {
    this.productId = productId;
    return this;
  }

   /**
   * id of product
   * @return productId
  **/
  @ApiModelProperty(required = true, value = "id of product")
  public Integer getProductId() {
    return productId;
  }

  public void setProductId(Integer productId) {
    this.productId = productId;
  }

  public Product productName(String productName) {
    this.productName = productName;
    return this;
  }

   /**
   * name of product
   * @return productName
  **/
  @ApiModelProperty(required = true, value = "name of product")
  public String getProductName() {
    return productName;
  }

  public void setProductName(String productName) {
    this.productName = productName;
  }

  public Product quantityOnHand(Integer quantityOnHand) {
    this.quantityOnHand = quantityOnHand;
    return this;
  }

   /**
   * quantity of product
   * @return quantityOnHand
  **/
  @ApiModelProperty(required = true, value = "quantity of product")
  public Integer getQuantityOnHand() {
    return quantityOnHand;
  }

  public void setQuantityOnHand(Integer quantityOnHand) {
    this.quantityOnHand = quantityOnHand;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Product product = (Product) o;
    return Objects.equals(this.price, product.price) &&
        Objects.equals(this.productId, product.productId) &&
        Objects.equals(this.productName, product.productName) &&
        Objects.equals(this.quantityOnHand, product.quantityOnHand);
  }

  @Override
  public int hashCode() {
    return Objects.hash(price, productId, productName, quantityOnHand);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Product {\n");
    
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    productName: ").append(toIndentedString(productName)).append("\n");
    sb.append("    quantityOnHand: ").append(toIndentedString(quantityOnHand)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

